import pandas as pd
from src.Model.data_processing import process_data
from src.Model.features import create_features_1, create_features_2
from src.Model.model_training import train_model_1, train_model_2

# read csv data generated by api script
result_data_model = process_data(pd.read_csv('../Data/matches3.csv'))

# create features with result_data_model
create_features_1(result_data_model)
create_features_2(result_data_model)

# train prediction model
model_1 = train_model_1(pd.read_csv('../Data/features_1.csv'))
model_2 = train_model_2(pd.read_csv('../Data/features_1.csv'))


